app:
  secret: mysecret
  name: auth
db:
  adapter: postgresql
  host: localhost
  user: postgres
  password: password
pagination:
  page_size: 10
rabbit_mq:
  consumer_pool: 10
logger:
  path: log/app.log
  level: info
